soundCategory: RECORDS

trident:
  - ==: me.JohnnyHT.velocityTridents.TridentData
    volume : 1.0
    pitch : 1.0
    customModelData : 1
    velocity : 2.0
  - ==: me.JohnnyHT.velocityTridents.TridentData
    volume : 1.0
    pitch : 1.0
    customModelData : 2
    velocity : 4.0

