name: VelocityTridents
version: '1.0-SNAPSHOT'
main: me.JohnnyHT.velocityTridents.VelocityTridents
api-version: '1.20'
commands:
  tridentreloadconfig:
    description: Reload the tridents
    permission: op
